### ISSUE TITLE
Migrate to styled components

### ISSUE THREAD

**Issue by jgleal** [onebeyond/shieldjs#108]
As stitches is no longer maintained #91 , we going to migrate to styled components

- [ ] Adopt stitches styles to styled ones
  - [ ] Common components
  - [ ] Home page @jgleal 
  - [ ] About page
  - [ ] Fetch example
  - [x] 404 @jgleal 
- [x] Implement a theme system

**Comment by jgleal** [comment]
Feel free to continue on https://github.com/onebeyond/shieldjs/tree/replace-stitches-by-styled-components

**Comment by acalvom** [comment]
**Last push**

- Migrate Button component
- Uninstall stitches
- General styles review
