### ISSUE TITLE
Stitches is no longer maintained - Discuss

### ISSUE THREAD

**Issue by Donivanes** [onebeyond/shieldjs#91]
![Image](https://github.com/onebeyond/shieldjs/assets/22077321/9dd7b3ec-c875-49c4-bad7-83899efad00c)

**Comment by Donivanes** [comment]
@jgleal Lealwind CSS tiene buena pinta, el destino

**Comment by Donivanes** [comment]
I want to propose this library: [Panda CSS](https://panda-css.com/) This one is having good reviews and also they have a migration explanation from stitches [here](https://panda-css.com/docs/migration/stitches)

**Comment by jgleal** [comment]
We gonna with Styled migration and we'll see
